title: <p align="center">M KAREEP NAVAS</p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <p ahref="https://www.linkedin.com/in/kareep-navas-4124a0123>Linkedin</p> | 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
